### ISSUE TITLE
d does not respect prefix count

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#2745] opened 2019-02-20 11:08 UTC
My expectation was that it is ok to prefix `d` with a number to repeat its action, same way `x` can be prefixed, but that's not the case. Any reason for that?

**Comment by Screwtapello** [comment] 2019-02-20 11:22
`d` deletes the selected text from the document. `5d` would presumably delete the selected text from the document, leaving the selection empty, then delete that (empty) selection four more times.

`5x` in Vim is probably equivalent to `5Ld` in Kakoune. That's one of the few times that Kakoune requires more keys than Vim to do a thing, but it's because Kakoune keeps "move the selection" and "delete the selection" separate, while Vim has a special key (`x`) that combines them.

**Comment by lenormf** [comment] 2019-02-20 11:42
Dupe of #2033.

**Closed** 2019-02-20 15:09 UTC
