### ISSUE TITLE
Boost not found when building manually

### ISSUE THREAD

**Issue by nonphoto** [mawww/kakoune#987] opened 2016-12-14 21:11 UTC
I am unable to build using `make` on macOS Sierra, but I have no issues installing Kakoune with Homebrew. It appears that Boost is not found:

```
In file included from color.cc:5:
./regex.hh:8:10: fatal error: 'boost/regex.hpp' file not found
#include <boost/regex.hpp>
         ^
```

Boost is installed with Homebrew:

```
boost: stable 1.62.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/usr/local/Cellar/boost/1.62.0 (12,405 files, 396.4M) *
  Poured from bottle on 2016-12-12 at 19:49:33
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb
==> Dependencies
Optional: icu4c ✔
==> Requirements
Optional: mpi ✘
==> Options
--c++11
	Build using C++11 mode
--universal
	Build a universal binary
--with-icu4c
	Build regexp engine with icu support
--with-mpi
	Build with MPI support
--without-single
	Disable building single-threading variant
--without-static
	Disable building static library variant
--HEAD
	Install HEAD version
```

**Comment by casimir** [comment] 2016-12-14 21:20
Don't you need to set `$PKG_CONFIG_PATH` correctly to find the boost version of homebrew?

**Comment by nonphoto** [comment] 2016-12-14 23:50
I tried `export PKG_CONFIG_PATH="/usr/local/Cellar/"` with no results. I thought that `Cellar` was in the path by default anyway?

**Comment by casimir** [comment] 2016-12-15 07:31
My bad I mixed up with ncurses, I use `PKG_CONFIG_PATH=/usr/local/opt/ncurses/lib/pkgconfig` to compile kakoune with then curses version from brew. Could it be the same issue than #974?

**Comment by lenormf** [comment] 2016-12-15 09:26
Dupe of #974.

**Closed** 2016-12-15 15:53 UTC
