### ISSUE TITLE
comment-block and Haskell

### ISSUE THREAD

**Issue by brynedwards** [mawww/kakoune#1600] opened 2017-09-28 11:54 UTC
Hi. Block comments in Haskell are `{-like this-}`. In [comment.kak#L120](https://github.com/mawww/kakoune/blob/master/rc/core/comment.kak#L120), the actual exec to comment is:

`exec -draft %{a${closing}<esc>i${opening}}`

Which, with Haskell's opening and closing, becomes:

`exec -draft %{a-}<esc>i{-}`

Which adds block comments `{-}like this-`.

**Comment by occivink** [comment] 2017-09-28 12:14
A possible solution would be to use different string delimiters than {}. I think %@...@ wouldn't cause much (if any) collision with comments.

**Comment by danr** [comment] 2017-09-28 12:18
The only two languages that use `@` in comments listed on http://rosettacode.org/wiki/Comments  are _Peloton_ and _TXR_.

**Comment by occivink** [comment] 2017-09-28 12:23
^ looks good too

**Comment by brynedwards** [comment] 2017-09-28 14:43
I think changing just the delimiters on line 120 causes the `}` to interfere with parent delimiters, so we'd have to change all parent delimiters to unique non-conflicting delimiters since we can't nest them. This, for example, works...

```
printf %s\\n "eval -draft %^ try %@
    # The selection is empty
    exec <a-K>\\A[\\h\\v\\n]*\\z<ret>

    try %&
        # The selection has already been commented
        exec %{<a-K>\\A\\Q${opening}\\E.*\\Q${closing}\\E\\n*\\z<ret>}

        # Comment the selection
        echo -debug %{${opening} ${closing}}
        exec -draft %_a${closing}<esc>i${opening}_
    & catch %{
        # Uncomment the commented selection
        exec -draft %{s(\\A\\Q${opening}\\E)|(\\Q${closing}\\E\\n*\\z)<ret>d}
    }
@ ^"
```

but even if the delimiters don't conflict it's still pretty hacky and inelegant in my opinion.

**Comment by occivink** [comment] 2017-09-28 15:52
A possibility would be to get rid of the shell scope and directly use 
`exec "<a-K>\A\Q%reg{o}\E.*\Q$%reg{c}\E\n*\z<ret>"`
where `o` and `c` would contain the exec_proof'd delimiters.

**Comment by lenormf** [comment] 2017-09-29 04:52
Dupe of #875

**Closed** 2017-11-24 08:38 UTC
