### ISSUE TITLE
-match-capture does not appear to be working correctly

### ISSUE THREAD

**Issue by Jackojc** [mawww/kakoune#4111] opened 2021-03-21 09:51 UTC
Hello.

I'm trying to write a highlighter for my language which has a funky kind of raw string syntax.

Raw strings take the form `\br([^\s])("|').*("|')(^[\s])` which ends up looking like `r#"hey"#` or `r~"hello"~` in use.

The thing that makes these strings a bit odd is the fact that the delimiter can be any single UTF-8 character but it has to match on both sides obviously.

### Steps 
I have this highlighter currently:
```
add-highlighter shared/wpp/raw_string region -match-capture %{\br([^\s])("|')} %{(?:"|')([^\s])} fill string
```
It is entirely possible I am using this incorrectly as I've seen that the Rust syntax file uses something sort of similar for its raw strings.

### Outcome 
So this highlighter _sort of_ works but not quite. If you view this in the editor, it will highlight strings like `r#"hello"#` correctly but not the empty string `r#""#` nor strings with quotes at the end of them (it works with quotes at the start for some peculiar reason, only when the source is exactly `""#` does it fail) `r#"hello""#`.

### Expected 
I would expect it highlight properly I guess but maybe I'm missing something. If I am, it at least seems intuitive and could use some better documentation.

**Comment by mawww** [comment] 2021-03-28 21:59
Hello, I think the issue here is that you want the first capture from the opening regex to match the second capture from the closing one and vice versa.

Its quite possible that the documentation is not very clear, but currently `-match-capture` only compare the first capture group of each (hence the singular). 

I think in your case you want to split it in two highlighters: the single quote and double quote ones, and have a capture to match on the `[^\s]` part.

**Comment by Jackojc** [comment] 2021-03-28 22:08
Hmm, you mean like:
```
add-highlighter shared/wpp/raw_string_dquote region -match-capture %{\br([^\s])"} %{"([^\s])} fill string
add-highlighter shared/wpp/raw_string_squote region -match-capture %{\br([^\s])'} %{'([^\s])} fill string
```
?

This also doesn't appear to work. I'm probably doing something wrong so bear with me :sweat_smile:

**Comment by mawww** [comment] 2021-03-28 22:42
That seems to work here:

```
add-highlighter global/test regions
add-highlighter global/test/ region -match-capture %{\br([^\s])"} %{"([^\s])} fill string
add-highlighter global/test/ region -match-capture %{\br([^\s])'} %{'([^\s])} fill string
```

So it could be that the issue is somewhere else in your setup.

**Comment by Jackojc** [comment] 2021-03-28 23:46
Oh wow, I figured it out and I feel pretty dumb now. So what was happening was `([^\s])` would also grab `"` and cause the highlighter to fail. So say you had `r#""#`. It would check the first quote and then grab the one next to it and consider that the end of the string. To fix it, I just changed the second regex to `"([^\s"])`.

**Comment by mawww** [comment] 2021-03-29 00:50
Ahh ok, I was testing with non empty strings, I guess that means we can close this issue.

**Closed by mawww** 2021-03-29 00:50 UTC
Labels: bug

**Comment by Jackojc** [comment] 2021-03-29 01:45
Thanks for the help anyway!
