### ISSUE TITLE
Paragraph objects do not support repetition

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1092] opened 2016-12-29 00:48 UTC
Press `2}p` or `2]p` with the cursor on the top of this buffer:
    
    a
    
    b
    
    c
    
I expect both paragraphs `a` and `b` to be selected, but only the first one is.

**Comment by lenormf** [comment] 2017-01-08 18:00
Duplicate of #795.

**Closed** 2017-01-28 16:34 UTC
