### ISSUE TITLE
Cant scroll upwards in file with wrapped lines

### ISSUE THREAD

**Issue by SolitudeSF** [mawww/kakoune#3000] opened 2019-07-01 17:09 UTC
launching kakoune with ` kak -n -e "addhl global/ wrap -word -indent"` and adding a lost of wrapped lines result in being unable to scroll upwards so the cursor leaves the view. Scrolling downwards is not affected.

**Comment by lenormf** [comment] 2019-07-02 06:07
I think this is a dupe of #1517, except the symptoms are triggered with a scroll rather than <kbd>pgup</kbd>.

**Closed** 2019-07-02 06:12 UTC
