### ISSUE TITLE
show_matching highlighter to show matching (opener|closer) character while typing

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#120] opened 2014-05-13 07:59 UTC

**Comment by lenormf** [comment] 2016-01-26 20:26
This has been implemented.

**Comment by lenormf** [comment] 2017-04-14 14:56
I think this issue can be closed.

**Comment by mawww** [comment] 2017-04-17 20:13
I think this references more the display of matching character when in insert mode, as once you type `)`, the cursor is not onto that character anymore, but on the next one, so you dont see which `(` you just closed.

**Comment by lenormf** [comment] 2017-04-17 20:20
That's what I thought as well, and I've provided an [implementation](https://github.com/mawww/kakoune/issues/1192#issuecomment-277637280) in a dupe of this issue a while back.

**Closed** 2018-01-19 02:30 UTC
