### ISSUE TITLE
Installing syntax highlighting packages

### ISSUE THREAD

**Issue by cvoege** [mawww/kakoune#957] opened 2016-12-13 15:43 UTC
Does kakoune support installing packages like [vim-polyglot](https://github.com/sheerun/vim-polyglot) so you don't have to add your own highlighters? If so how do you do it? Because there's literally no documentation on it and it seems like a common requirement to use the editor.

**Comment by doppioandante** [comment] 2016-12-13 16:24
All the available highlighters are bundled with the editor for now, the documentation about highlighters is in the [readme](https://github.com/mawww/kakoune#88-highlighters) but it is probably easier to take on of the existing scripts as a starting point.

**Comment by cvoege** [comment] 2016-12-13 19:35
I saw that in the readme, but I most certainly don't have time to write highlighting regex rules for every single language I use that isn't supported yet.

I'm looking for JSX syntax highlight is there no option for me?

**Comment by doppioandante** [comment] 2016-12-13 20:11
We should have basic javascript support already, but no JSX as far as I know.

**Comment by cvoege** [comment] 2016-12-13 20:20
I compiled it myself, everything worked fine in make. No JS highlighting though, all code is white (though the text on the last line of the editor is blue, so it's using the terminals colors just fine.) 

Are there any plans for a package manager or anything which would allow things like sharing syntax highlightings and themes? This editor will be a non-starter for a lot of people if they can only use the limited set of languages you provide highlighters for.

**Comment by doppioandante** [comment] 2016-12-13 20:28
Did you run make install?

As for the other point, a package manager and the lack of language support are two different issues.
There is no plan for those, kakoune has few users and we usually contribute whatever we come up with to upstream, some of us use git to handle out-of-tree extensions.

A package manager of some sort is certainly possible, while support for more languages would be tricky (it's not only syntax: indentation, tooling etc).
For syntax highlighting alone, maybe we could rely on an external fallback utility that does the highlighting for us and if I remember correcly @lenormf looked into it.

**Comment by cvoege** [comment] 2016-12-13 20:32
Did you ever consider making your syntax highlighting engine compatible with another editors? That way porting the highlighters would be easy and you could build a nice community around it.

Also why is the `sudo make install` call not included in the install directions?

**Comment by doppioandante** [comment] 2016-12-13 20:39
>  Also why is the sudo make install call not included in the install directions?
It's mentioned in the readme, section 2.2 (Installing)

> Did you ever consider making your syntax highlighting engine compatible with another editors? That way porting the highlighters would be easy and you could build a nice community around it.
It's probably better for mawww to answer this.

**Comment by cvoege** [comment] 2016-12-13 20:47
Oh I see, in the beginning of the README there's a TLDR, but it doesn't include sudo make install, which I think 99% of people installing will want to do so they get it in there path and so syntax highlighting works.

**Comment by mawww** [comment] 2016-12-14 00:55
Hello,

There should be no need to do `make install` to try out kakoune, it should run just fine from the src/ directory, and load all the bundled scripts.

It is strange this did not work for you, did you move the built 'kak' file around ?

In order to work both from the source directory and from installed directory, kakoune relies on relative paths, it assumes it will find `../share/kak/kakrc` (this is *not* the user config, but the global startup script, which among other things will load the user config from `$XDG_CONFIG_HOME/kak/kakrc`).

If you copied the kak binary to a bin folder manually, this will fail. Using a symlink to the kak binary will work though.

**Comment by cvoege** [comment] 2016-12-14 03:52
There's no NEED to, but it makes it a whole lot easier to try out when you can cd ~/mycode/ and just say kak code.js

**Comment by lenormf** [comment] 2016-12-14 05:40
@cvoege put a `~/bin/` directory in your `PATH`, and add a symlink from `~/bin/kak` to the binary.

**Comment by mawww** [comment] 2016-12-14 13:57
@cvoege Was the initial lack of syntax highlighting caused by a moved kakoune binary ?

**Comment by mawww** [comment] 2016-12-15 23:59
I'll assume that was it for now, closing.

**Closed by mawww** 2016-12-15 23:59 UTC

**Comment by danr** [comment] 2018-02-04 07:37
@cvoege JSX support will be merged soon, see #1796
