### ISSUE TITLE
Can't open a file with a '$' sign

### ISSUE THREAD

**Issue by blastrock** [mawww/kakoune#1545] opened 2017-08-27 21:07 UTC
This line, in a shell:

```sh
kak 'foo$bar'
```

opens a file called just 'foo', which is quite unexpected.

**Comment by mawww** [comment] 2017-08-28 06:21
This is due to Kakoune expanding env vars in filename (which I am not sure is such a nice behaviour), so `$bar` expands to an empty string and the remaining filename is `foo`.

**Comment by lenormf** [comment] 2017-08-28 10:32
Couldn't `parse_filename` simply replace `~` with whatever value is stored in `$HOME`, rather than substitute the former with the latter and then parse any and all shell expansion in the path?

**Comment by blastrock** [comment] 2017-08-28 10:54
I would expect that no replacement at all is done there. I want to be able to edit a file named '~' too. Since no editor does it, such a behavior would be very unexpected.

If I want ~ or $ expansion I can use the shell indeed

```sh
kak ~/myfile $HOME/myfile
```

And if I want to use kakoune variables (which is strange I think...), I guess I could do it with something like:

```sh
kak -e 'edit %val{session}'
```

**Comment by lenormf** [comment] 2017-08-28 11:15
@blastrock the issue is that the path passed to `kak` from the command line is handled by the `parse_filename()` function, which also handles the path passed to the `:edit` editor command. In the latter case we want to handle the `~` character, and the current implementation of the function replaces `~` with `$HOME`, but also subsequently parses all shell variable expansions in the path.

This will be fixed, just hang around.

**Comment by mawww** [comment] 2017-08-29 00:56
Yep, I agree this should be changed, I think we want to keep tilde expansion in filenames, but env vars expansion is something that I put in place in Kakoune's early code with not much tought, so I believe its better to remove it now.

**Closed** 2017-08-29 03:39 UTC
