### ISSUE TITLE
Visual line up/down (gj + gk in vim)

### ISSUE THREAD

**Issue by losnappas** [mawww/kakoune#2851] opened 2019-04-11 21:28 UTC
Hello,

plenty of times I have a long, long line that is wrapped on multiple lines. The legit way of going downwards is by spammin W, as far as I know. I'd like the `gj` from vim, which goes downward one visual line, so that includes wrapped lines.

Does that already exist? Which key? thx

**Comment by Screwtapello** [comment] 2019-04-11 21:57
This isn't really possible on Kakoune, because the editing language is also part of the scripting language (via `:execute-keys`), so it needs to work the same way every time. Meanwhile in Vim, `gj` from the same starting point can take you to very different places depending on the width of the window.

It's annoying, but nobody's figured out how to square that particular circle yet.

**Comment by andreyorst** [comment] 2019-04-12 10:23
> The legit way of going downwards is by spammin W, as far as I know

I've struggled wit this at first, but learned to use search every time I need to move around long lines. There's also some plugins for moving around the buffer, but I really miss the [vim-sneak](https://github.com/justinmk/vim-sneak) feature for that.

**Comment by losnappas** [comment] 2019-04-12 11:24
If Kakoune has the current cursor placement relative to the full line length, meaning it'll give me like "120" even if I'm visually at first column thanks to linewrap, stored somewhere, then shouldn't it be possible to:

1. Feed the line into `wc` to get char count
1. Get pane width from tmux
1. Simple arithmetic and execute `l` enough times to put me 1 line below

it doesn't even need to be a perfect count, just close enough would do. Thoughts? If that variable doesn't exist, then possible to implement? Seems useful enough

**Comment by andreyorst** [comment] 2019-04-12 11:55
`:echo %sh{tput cols}` prints width of terminal window in columns. But you need to remember that Kakoune UI takes space too. Like line numbers can take various amounts of columns.

**Comment by Screwtapello** [comment] 2019-04-12 11:57
Yes, that would work - the value you're looking for is `%val{cursor_char_column}`, I think (there are other `cursor_*` values that might be more appropriate)

However, wrapping doesn't necessarily occur exactly every `$COLUMNS` characters — the wrap highlighter has a bunch of options which each cause wrapping to be narrower. In `-word` mode, each line of a paragraph could be a different length.

**Comment by losnappas** [comment] 2019-04-12 11:59
All of that is somewhat irrelevant to me. I just want to go down a line, doesn't have to be exact.

How do I do the step 1 without wrecking current selections? The rest of it seems easy enough, with the tput cols I don't need tmux things, either.

**Comment by losnappas** [comment] 2019-04-12 12:43
I guess the low hanging fruit is here

```
define-command move-visual-line -params 1 %{
    execute-keys %sh{
        n=$(tput cols)
        printf "%s\n" "${n}$1"
    }
}

map global goto j '<esc>: move-visual-line l<ret>'
map global goto k '<esc>: move-visual-line h<ret>'
map global goto J '<esc>: move-visual-line L<ret>'
map global goto K '<esc>: move-visual-line H<ret>'
```

Has all the problems you mentioned, but it'll do for awhile.

**Comment by Screwtapello** [comment] 2020-04-23 07:37
Apparently this is a duplicate of #1425.

**Closed** 2020-04-23 10:57 UTC
