### ISSUE TITLE
<a-a>r and <a-i>r broken with tight nesting

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#2367] opened 2018-09-07 14:49 UTC
### Steps 

Edit this as `foo.clj`:
```
     
     [[?p :program/prospect-form-grouping ?eid2]
      [(str "Prospect form grouping " ?pf-name
            " must start with " ?prefix-uname) ?msg]]
```

Put cursor on first or last square brace and type `<a-a>r` (or `<a-i>r`).

### Outcome

From the second up to the third brace, inclusive, is selected (with `<a-a>`).  Or, from the second brace (inclusive) up to the third brace (exclusive) is selected. 

### Expected

The whole block is selected (with `<a-a>`) or everything except the outermost braces are selected (with `<a-i>`).

**Comment by Delapouite** [comment] 2018-09-07 16:08
This behavior was fine in v2018.04.13. It changed in https://github.com/mawww/kakoune/commit/148d6

**Comment by Delapouite** [comment] 2018-09-08 17:27
This issue seems a duplicate of https://github.com/mawww/kakoune/issues/2129

**Closed** 2018-09-12 11:28 UTC
