### ISSUE TITLE
Infinite loop with alt-a : ,.

### ISSUE THREAD

**Issue by kballard** [mawww/kakoune#994] opened 2016-12-15 00:15 UTC
As documented in #992, if I position the cursor somewhere on a line that has a `.` later, and press `alt-a : ,.`, Kakoune enters an infinite loop sucking up 100% CPU and ignores ^C, and must be killed externally. I'm using a binary built from 430ff37. This bug is not specific to `,.`, you can replace the `.` with any other character as long as that character exists on the line after the cursor.

**Comment by lenormf** [comment] 2016-12-15 09:23
This issue is a dupe of #992.

**Closed** 2016-12-15 09:30 UTC
