### ISSUE TITLE
Install error on Manjaro/Arch

### ISSUE THREAD

**Issue by narimiran** [mawww/kakoune#1817] opened 2018-01-27 12:44 UTC
I'm trying to install Kakoune on Manjaro Linux, using AUR.

I have an option to install version `r5975.baf3d82b-1` (last update: 2018-01-02 20:18), but when I run the install I get this error:

```
Resume: 317 tests, 4 failures
make: *** [Makefile:101: test] Error 4
==> ERROR: A failure occurred in check().
    Aborting...
==> ERROR: Makepkg was unable to build kakoune-git.
```

1. What is going on?
2. Should AUR package be updated?
3. Any way to bypass this in the mean time and successfully install Kakoune?

**Comment by patricksjackson** [comment] 2018-01-27 23:21
You should probably be asking for help on the AUR: https://aur.archlinux.org/packages/kakoune-git/

I have no problems building and installing it on Arch, but it looks like you are hitting failures while running `check()` in the PKGBUILD. My wild guess is that 4 of the tests may have some dependency not listed in the PKGBUILD that you happen to not have installed. Make sure that you report which of the tests are failing so someone can help track down why.

The "forced" workaround is to edit the PKGBUILD to just remove the `check()` function, but  that may result in issues with using kakoune.

**Comment by lenormf** [comment] 2018-01-28 07:01
Try compiling the project my hand, see if you can reproduce it (and potentially get a more verbose error).

Note that I'm compiling nightly packages for Archlinux on my own server, if you need a package quickly:

https://ironzorg.fr/kakoune-nightly/

**Comment by narimiran** [comment] 2018-01-28 08:07
> if you need a package quickly: https://ironzorg.fr/kakoune-nightly/

This was successful.

**Comment by mawww** [comment] 2018-01-30 22:44
I think I already had this error of the test suite here, it happens when the test suite runs with a non utf8 locale, leading to some text not being outputted correctly.

**Comment by lenormf** [comment] 2018-06-30 10:33
I think we can close this issue now that the problem has been resolved.

**Comment by Delapouite** [comment] 2019-05-06 15:11
@narimiran Hi. Do you mind closing this issue which appears to be resolved? Thanks.

**Closed** 2019-05-06 15:12 UTC
