### ISSUE TITLE
Git commands only process a single file

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2869] opened 2019-04-21 02:53 UTC
**Example** – Adding 2 files:

``` kak
git add 01.txt 02.txt
```

Only `01.txt` is added.

**Comment by nonumeros** [comment] 2019-04-23 04:29
I'm not so sure what the current implementation of git under kakoune is about, but I can't hide my surprise that it looks quite similar to https://github.com/tpope/vim-fugitive (http://vimcasts.org/episodes/fugitive-vim---a-complement-to-command-line-git/) except with the side effect (afterthought) that invoking `git status` shows a number of untracked files from the parent directories. This is not the right approach.

**Comment by nonumeros** [comment] 2019-04-23 08:51
In other words, so there's no misunderstanding here. If on current working directory, the git status` should only show what the status is supposed to be for that working directory, and not for untracked/unstaged parent directories' files elsewhere. Perhaps is the intrinsic nature of kak by creating backup files... I don't know, but I didnt like what I see.

**Comment by Screwtapello** [comment] 2019-04-23 09:12
Regular `git status` on the command-line shows the status of the entire repo, not just files within the current directory:

    $ git status
    On branch master
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)
    
    	modified:   ../Cargo.toml
    	modified:   main.rs
    
    no changes added to commit (use "git add" and/or "git commit -a")

Why should Kakoune's `git status` wrapper be any different?

**Comment by nonumeros** [comment] 2019-04-23 12:25
To answer I'm going to let someone on my behalf do it for me. Note I don't like it , but it might give you a different perspective of whats at stake here, and it helps me out to ito produce the thoughts in a Wittgensteinian the limits of my language are the limits of my world

You asked
>Why should Kakoune's git status wrapper be any different?

The answer
>It's not a 1:1 wrapper that allows using the editor as a shell,
Source: https://github.com/mawww/kakoune/issues/2865#issuecomment-485062546

You said
>Regular git status on the command-line shows the status of the entire repo, not just files within the current directory:

The reply
>The point of this file is to interact with Git commands that return data that is meaningful to the editor.
Source: https://github.com/mawww/kakoune/issues/2865#issuecomment-485062546

Unfortunately, as you probably suspect, @lenormf  views and mine sit in such opposite sides that you'd probably think I would agree with you, but I  don't, and neither with him, since meaningful for him would be calling it out from the shell, and since you are comparing the expected behavior of the meaningfulness of the editor, with the output of a shell... Remember you said earlier that quote: Regular git status on the command-line shows the status endquote. , it seems to me that both of your are in such contradictory terms to the point - or so I think - that I can't think of a common ground between both of you. 

For him the thought process is  leave it all out there for the external program to handle, at the end of the day, git's business shouldn't be the editors' business, except the part about meaningfulness that should be reserved to the editor (whatever that means), and for you is about confirming why does it need to be any different than the external git program itself. But I can 't read between lines or trying to imagine based on a question what you may have implied, but the question `Why should kakoune wrapper be any different?` ratifies what you might want to confirm. 

Are there any git blobs out on the working directory? Most likely not since that's exclusively generated from git itself. But if we were to leave it at the mercy of the editor then your message that reads `no changes added to commit (use git add)` might very well turn out to be `nothing added to commit but untracked files present (use git add to track)` as well. 

Recently,  and I meant to say recently here, by years, git implemented a prompt config feature of email. and user.name settings right after trying to submit a commit without it, which I've always found it handy. Istill remember the time when that feature wasn't there, and regardless of the method that the editor uses to commit, there's no doubt that in order to commit, this config must have been set on the system somewhere. The question is whether the editor should supplement it, adhere to it, or work around it.

**Comment by nonumeros** [comment] 2019-04-24 07:15
vim git plugin inception was around 2010, https://en.wikipedia.org/wiki/Fugitive.vim, but it didn't matured until around 2015. By that time plenty of git features had already been introduced. 

There's nothing meaningful about just `add`ing [files], then `commit`ing without fully knowing - of course `status` would return the answer - the consequences of both arguments accordingly.. Nothing meaningful really, but just a bunch of untracked and/or unstaged files in the process. Kak users ought to keep a cheat sheet for git-editor commands and another for git commands besides it . 

But without sounding pedantic here., and from the shell.

     $cd dir
     $kak edit and save file1
     $git add file1
     $git status
     new file file1
     ../.file1.kak.123
     ../.file2.kak.456

Now back to the same example but with init this time around

     $cd dir
     $kak edit and save file1
     $git init
     $git add file1
     $git status
     new file file1


I also checked the plugin for vim and I wasn't impressed for the simple reason
that is a useless plugin without a blob.  The problem with kak on the other
hand, is that it picked up where the vim plugin left off, and one would think
that  it would have evolved by now, but it didn't, because it used the same
underlying philosophy to implement commands than what the plugin from vim had
used, even though the latter is useless again without a blob. I do think that
kak is more capable than that because as I said before, of its intrinsic nature
of working with buffers, files and so forth. Of course, to confirm why the current git
design fails on both vim and kak , one could visit the following link
where the problem with the path  came up, to see the resemblance [how to git add
with fugitive](https://stackoverflow.com/questions/35812319/)

**Comment by nonumeros** [comment] 2019-04-24 07:52
It's not hard to see the vim plugin failure to even remotely consider  the possibility of having something as `init`. Let alone the remainder myriad of Linus creation, It's useless without a blob. It needs a blob as a mandatory companion to even function!

**Comment by mawww** [comment] 2019-04-24 13:26
The reason `git add` only consider the first argument is that it was simpler to implement like that at the time, especially as I wanted `git add` with no argument to add the current file. Arguably it should just forward all its arguments to `git add` and only pass the current buffer filename automatically if given no argument.

**Comment by aThorp96** [comment] 2019-10-04 01:09
Is this issue still active?

**Comment by mawww** [comment] 2019-10-09 06:41
Thanks for reminding me of that.

**Closed** 2019-10-09 06:41 UTC
