### ISSUE TITLE
Cannot select newline character in normal mode

### ISSUE THREAD

**Issue by occivink** [mawww/kakoune#530] opened 2015-12-14 19:59 UTC
Hi,

I may be missing something, but it doesn't seem possible to put the cursor over the line feed in a line using the usual movement keys (```l```, ```<a-l>```, ```gl``` ...). 
This makes it somewhat inconvenient to insert text at the end of the line (one could use ```a``` on the last character, but this selects everything being typed), or to just join two lines by removing the line feed.
A possible way to select it is to use ```x;``` but it is somewhat limited.

Of course, none of this applies if the line is empty as the cursor can only be on the newline character, which seems inconsistent to me.

**Comment by greduan** [comment] 2015-12-14 22:11
So you want to open a new line? Just use `o`, standard in Vim as well. Or `O` for newline above the current line.

**Comment by doppioandante** [comment] 2015-12-14 22:22
Maybe having x; do nothing on the empty line (actually: selecting the empty string + newline) could be a solutions?
It would at least solve the inconsistency, if I've understood correctly

**Comment by greduan** [comment] 2015-12-14 23:47
If one wants to open a newline it's inefficient to go to the end of the line and press `a` and insert a new line, or go to the beginning of a line and press `i` and insert a new line.

The proper way to do this in vi-like editors is `o` and `O`.

**Comment by mawww** [comment] 2015-12-15 02:12
`x;` would be the preferred way, avoiding the eol with other commands is by design, and most use cases are already handled with `A`, `o` and `<a-j>`

**Comment by occivink** [comment] 2015-12-15 11:35
it's not really about opening a newline or specific operations. Most use cases are indeed covered by different commands, but for example I'd rather use explicit commands like `ghi` than `I` and currently there is no similar equivalent to `A`. For what it's worth, I tried the following patch
```
diff --git a/src/normal.cc b/src/normal.cc
index 839093a..698eb93 100644
--- a/src/normal.cc
+++ b/src/normal.cc
@@ -1457,7 +1457,7 @@ void move(Context& context, NormalParams params)
         sel.anchor() = mode == SelectMode::Extend ? sel.anchor() : cursor;
         sel.cursor() = cursor;
     }
-    selections.avoid_eol();
     selections.sort_and_merge_overlapping();
 }

diff --git a/src/selectors.hh b/src/selectors.hh
index fff025f..8b92b63 100644
--- a/src/selectors.hh
+++ b/src/selectors.hh
@@ -133,7 +133,7 @@ Selection select_to_line_end(const Buffer& buffer, const Selection& selection)
 {
     ByteCoord begin = selection.cursor();
     LineCount line = begin.line;
-    ByteCoord end = utf8::previous(buffer.iterator_at({line, buffer[line].length() - 1}),
+    ByteCoord end = utf8::character_start(buffer.iterator_at({line, buffer[line].length() - 1}),
                                    buffer.iterator_at(line)).coord();
     return target_eol({only_move ? end : begin, end});
 }
```
and I think I like this behavior better. With this I can insert at the end of a line using `gli`

**Comment by lenormf** [comment] 2015-12-15 11:53
A line is made of all the characters between `^` and `$` excluded, and the implementation of the commands wouldn't make sense if they weren't based around that concept.

`gl` takes you to the last character of the current line, having it put the cursor on the newline character (which is merely a separator, not a part of the line) breaks that contract.

By your logic, we could also have `gh` put the cursor on the newline character of the previous "line", but the fact that it didn't occur to you might reveal that your vision of stream edition is funneled through the mainstream way of doing things (vim et al). The "cursor" in `kak` is not a location, it's a selection whose two ends can be concurrent, and like I said above, commands are implemented around this concept.

**Comment by occivink** [comment] 2015-12-15 12:00
It seems like the only difference between your description and my understanding is whether `$` is included or not in a line. Is that a key concept in kakoune?

**Comment by lenormf** [comment] 2015-12-15 12:09
I can't formally say it, but I think the way certain commands work (more particularly the way they do not include newlines when used) gives us a big hint: `gl` is a good example, although I must say `x` is also a counter example to that.

**Comment by occivink** [comment] 2015-12-15 12:53
Well yes the movement commands seem to avoid the eol character but that's what I'd like to understand. 

Besides, it seems like this definition of a line falls short with empty lines, in which case the cursor is placed over the eol character.

**Comment by lenormf** [comment] 2015-12-15 13:15
There's no EOL on an empty line by default, but yes the cursor will be over the newline character if there's nothing else on the same line.

**Comment by mawww** [comment] 2015-12-15 13:49
AFAIR, avoiding eol on movement commands is mainly because it did not feel right to me when I experimented with it. In my opinion not treating eol specially would be more consistent, but it seemed in practice I did not want `l` to move to the end of line.

I am not against revising this behaviour, that might simplify some things, complicate others, a search in existing commands in `rc/` could reveal what is the most common case.

**Comment by occivink** [comment] 2015-12-15 15:23
Allowing explicit move over eol (e.g. using `l` on the last non-eol character of a line) seems like a no-brainer to me as it only extends a no-op and improves consistency (also offers some functionality). 

Including eol in `gl` and `<a-l>` would be trickier as the command would have a different result in all cases.

I haven't seen any use of `gl` and a few of `<a-l>` in `rc/` but they could be adapted, so I think the biggest consideration is whether it is actually preferable to avoid eol or not.

**Comment by doppioandante** [comment] 2015-12-15 22:14
I agree with @occivink on l moving over eol.
The reason is simple: kakoune is special because the cursor is always a selection.
In traditional text editors, the cursor is simply a position that specifies where text will be inserted, and there is no doubt about its behaviour on newline: either I want to insert text before the eol, in this case the cursor will be positioned at the very end of the line, or I want to insert text after the eol, then it will be on the next line.

It doesn't make much sense that selecting skips the newline feed: in fact, if you try to hold shift and press left at the end of the line in a notepad-like text editor, it will select the newline (the visual feedback is the whole line after the cursor becoming selected).

However changing the current behavior is not as easy as changing l, gl, x and so on.
We should reconsider also things like w, that currently skips the newline (but not the space after words in general). Same story for A and all the basic selection primitives.

**Comment by mawww** [comment] 2015-12-15 23:24
I guess we could experiment with it, see if it works well.

Note that the change will probably change the behaviour of `j` and `k` as well, as they try to avoid end of line (and are implemented in the same function as `l`), so `j` could move down directly on an eol.

Also, that means that eol targetting would be moved to the eol char, not the previous one (eol targetting is what happens when you use `j` or `k` after a `gl` (for example), where the cursor will get on the last char of the line even if its longer than the current line.

**Comment by lenormf** [comment] 2015-12-16 13:41
This would be a lot of work for no gain whatsoever, since all commands already allow us to insert text and move around the buffer anywhere we want, newline ignore or not.

**Comment by mawww** [comment] 2015-12-16 16:45
the change is quite easy actually, as we can just comment the call to avoid_eol, the main interest is that we start considering eol as a non-special char, which seems to improve consistency, however (and thats what I want to see by experimenting with it), I suspect we will see that eol really wants to be treated specially, giving a proper justification to the current behaviour.

**Comment by GrantMoyer** [comment] 2016-03-04 23:44
For what it's worth, it was specifically inconsistencies like newlines being treated as special characters that made want to stop using Vim and made me interested in Kakoune. It seems to me that being able to move over a newline only seems unnatural after getting used to vim, because almost every other major editor behaves this way by default.

**Comment by mawww** [comment] 2016-09-05 12:38
This is now easy, we dont avoid end of lines on lateral movements anymore (we still try to when going up/down, but you can always go onto the end of line with `l`).

**Closed by mawww** 2016-09-05 12:38 UTC
