### ISSUE TITLE
Forward jump no longer working in kitty (regression)

### ISSUE THREAD

**Issue by jtrees** [mawww/kakoune#4333] opened 2021-09-08 11:22 UTC
### Steps 
- Open a scratch buffer
- Jump to end of buffer (`ge`)
- Jump back (`<c-o>`)
- Attempt to jump forward again (`<c-i>`)

### Outcome 
Nothing happens.

### Expected 
The selection should jump back to the end of the buffer.

### Comments
This appears to be a regression that was introduced somewhere between v2020.09.01 and v2021.08.28.

**Comment by Screwtapello** [comment] 2021-09-08 12:30
I cannot reproduce this problem with `kak -n` in GNOME Terminal, or in xterm.

**Comment by jtrees** [comment] 2021-09-08 14:58
Oh, interesting. I am using [kitty](https://sw.kovidgoyal.net/kitty/) but can confirm that it still works with GNOME Terminal.

**Comment by jtrees** [comment] 2021-10-01 09:31
The kitty maintainer wrote this:

> This will be a bug in kakoune's support of the extended keyboard protocol

Dunno if that helps.

**Comment by Screwtapello** [comment] 2021-10-01 12:56
I guess this should be marked as a dupe of #4242

**Comment by jtrees** [comment] 2021-10-01 13:47
Ah, that makes sense.

**Closed** 2021-11-03 09:24 UTC
Labels: bug

**Comment by jtrees** [comment] 2021-11-09 12:36
I'd like to re-open this. PR #4415 fixed most key-combos for me but <c-i> still isn't working.

**Comment by mawww** [comment] 2021-11-11 02:31
Should be fixed now.

**Comment by jtrees** [comment] 2021-11-12 20:58
Yay! It works! Thanks a bunch. <3
