### ISSUE TITLE
Extra selection after undoing automatic un-indent of a tab

### ISSUE THREAD

**Issue by krobelus** [mawww/kakoune#3130] opened 2019-10-09 21:42 UTC
### Steps
```sh
printf '\tfi\n' | kak -e 'set global filetype sh'
```
Then type `o` to open a new line, `<esc>` and `u` to undo the edit.

### Outcome
There are two selections, one on each line.

### Expected
There should be only one selection, probably on the second line

**Comment by eraserhd** [comment] 2019-10-18 17:52
Duplicate of #753 and #1184 (which affect me frequently).

**Closed** 2020-09-02 17:19 UTC
