### ISSUE TITLE
Have to double press Esc to activate normal mode

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#1858] opened 2018-02-18 18:50 UTC
I edited simple golang file and noticed that when I reach typing `+ c` at the end of line `10`, hitting <kbd>Esc</kbd> once does not exit to normal mode. I had to hit <kbd>Esc</kbd> twice. Same behaviour with `go-disable-autocomplete`.

[![kak-_A420.gif](https://s25.postimg.org/70n6c56n3/kak-_A420.gif)](https://postimg.org/image/q5qflwlaz/)

At first I thought it is expected behaviour, i. e. first esc quits popup, second activates normal mode. But it is inconsistent. I mean if I press capital <kbd>A</kbd> from normal mode to edit the same line `10` again, the pop up appears as expected, but this time hitting single <kbd>Esc</kbd> quits to normal mode straight away.

**Comment by mawww** [comment] 2018-02-19 11:26
I cannot reproduce here, however something is strange on your recording, when you press `O` on the closing bracket to enter the sum, you do not get autoindentation on the new line. I do get it here, maybe something in your configuration is interacting ?

**Comment by vbauerster** [comment] 2018-02-19 18:06
I've updated `kak` to cbf11d7 and this time removed my `kakrc` at all.

[![kak-norc-420.gif](https://s18.postimg.org/6rjkikg09/kak-norc-420.gif)](https://postimg.org/image/98vbptzwl/)

As you can see it is same result. Maybe it is because of mac version?

**Comment by occivink** [comment] 2018-02-19 18:58
Is that tmux? Could it be [this issue](https://github.com/mawww/kakoune/blob/master/doc/pages/faq.asciidoc#why-does-leaving-insert-mode-take-more-than-half-a-second-in-tmux-)?

**Comment by vbauerster** [comment] 2018-02-19 20:49
Yes it is inside tmux. Same behaviour without tmux.

**Comment by mawww** [comment] 2018-02-21 12:07
Aha ! got it, you are doing `<a-;>O` to open a line above the `}` of func sum !

Kakoune modes are stored in a stack with the top of the stack being the active mode, so, when writing your code, you have the following stack:
`<normal> <insert>` after `<a-;>` you have `<normal> <insert> <normal single key>`, then `O` enters insert mode *again*. As `<normal mode single key>` leaves before executing the given key, you end up with `<normal> <insert> <insert introduced by O>`. Once you hit `<esc>` for the first time, its `<insert introduced by O>` which quits, but the next mode on the stack is `<insert>`, so you need a second `<esc>` to get to normal mode.

I understand this can be surprising if you dont have in mind that modes are in a stack (if you imagine kakoune modes as states in a state machine for example).

So in the end, this is expected behaviour, I just did not realize  that you were doing `<a-;>O` in your samples.

**Closed by mawww** 2018-02-21 12:07 UTC

**Comment by vbauerster** [comment] 2018-02-21 20:01
Thank you for explanation, good to know.

**Comment by heyakyra** [comment] 2020-07-09 18:11
Didn't want to file a separate ticket yet since I'm a newbie and this could be user error, but I can't leave insert mode using the `esc` key at all when inside of tmux. Thankfully `<a-;>` lets me get things done but if I simply:

1. `tmux` open tmux
2. `kak` open kak
3. `i` insert
4. `<esc>` (as many times or as rapidly doesn't matter)
5. nothing happens

**Comment by Screwtapello** [comment] 2020-07-09 23:23
Inside Kakoune, please try running these commands:

    buffer *debug*
    set-option buffer debug keys

...which mean:

  - switch to the `*debug*` buffer, where Kakoune logs debug messages
  - in this buffer only, print a debug message for every key received

Then press Esc and see what key it reports. It should print something like:

    Client 'client0' got key '<esc>'

You may also want to try the same experiment when running Kakoune with `kak -n` to start in Safe Mode, just in case your configuration is broken in some way.

**Comment by heyakyra** [comment] 2020-07-10 01:41
Sorry, my description was incorrect, this happens when `tmux` is inside of `screen` (this is very useful to have `screen` running locally while connecting to multiple servers, and running `tmux` in each server remotely). Since this causes no issues for `vim` I think the problem is here. 

I attempted to do the debugging with `kak -n`, and rather than receiving `<esc>`, I see...

If I hit `<esc>` twice (first time does nothing):
```
Client 'client0' got key '<a-�>' 
```

If I hit `<esc>` once (no output), but then I click somewhere:
```

Client 'client0' got key '<a-�>' 
Client 'client0' got key '[' 
Client 'client0' got key '<lt>' 
Error: no selections remaining 
Client 'client0' got key '0' 
Client 'client0' got key '<semicolon>' 
Client 'client0' got key '1' 
Client 'client0' got key '2' 
Client 'client0' got key '3' 
Client 'client0' got key '<semicolon>' 
Client 'client0' got key '2' 
Client 'client0' got key '8' 
Client 'client0' got key 'M'                                
```

**Comment by Screwtapello** [comment] 2020-07-10 02:39
If you press a key-stroke like Alt-o, the terminal sends Kakoune the bytes 0x1b 0x6f.

If you press Escape, the terminal sends 0x1b, and if you then press "o", the terminal sends 0x6f.

How does Kakoune (or any other app) determine whether 0x1b 0x6f means Alt-o or "Esc, o"? The only way it can tell is by timing the delay between the bytes — anything below a particular threshold is treated as a single keystroke, otherwise the bytes are handled individually.

Multiplexers like GNU Screen and tmux make the problem worse, because they *also* need to determine whether a byte-sequence is a single keystroke or not, so it winds up like:

  - user presses Esc
  - terminal sends 0x1b to Screen
  - Screen starts a timer
  - Screen's timer runs out, so it decides the 0x1b is just Esc, and sends it along to tmux
  - the network takes some time to transmit the byte to the remote host
  - tmux starts a timer
  - tmux's timer runs out, so it decides 0x1b is just Esc, and sends it along to Kakoune
  - Kakoune starts a timer
  - User presses "o"
  - terminal sends 0x6f to screen
  - Screen's timer has already elapsed, so it sends the "o" to tmux
  - tmux's timer has already elapsed, so it sends the "o" to Kakoune
  - Kakoune's timer is still running, so it assumes the "o" is part of a single key-stroke, and executes the mapping associated with `<a-o>`

Looking at the debug messages you pasted, your "press Esc twice" message looks like Kakoune is treating it like `<a-esc>` (the fact that Kakoune doesn't print the key-name properly is a separate bug), which is a valid decoding of the bytes 0x1b 0x1b if they occur too quickly together. Likewise, a mouse-click event begins with byte 0x1b, so it looks like Kakoune misunderstood the `<esc><click>` sequence as `<a-esc>[<lt>...`.

An easy way to test this: do the `set-option buffer debug keys` thing again, then press Esc and wait ten seconds or so to see if `<esc>` eventually appears.

If the problem does turn out to be timeout related, there's no simple fix - you have to deal with each layer of timeout separately.

  - Released versions of Kakoune are built on the ncurses library, so you can set `$ESCDELAY` to a timeout in milliseconds
  - tmux has its own `escape-time` config option you can set in the tmux config file
  - GNU Screen probably has a config option too, but I don't know what it is off-hand

Vim doesn't appear to have these problems because it cheats - if it receives an Alt-o keystroke and there's no Alt-o mapping in the current mode, it deconstructs the keystroke back to separate Esc and "o" keystrokes. This isn't practical for Kakoune, because it has a lot more Alt-based mappings than Vim does.

**Comment by heyakyra** [comment] 2020-07-10 12:51
Thank you for that incredible explanation! 

> Vim doesn't appear to have these problems because it cheats - if it receives an Alt-o keystroke and there's no Alt-o mapping in the current mode, it deconstructs the keystroke back to separate Esc and "o" keystrokes. 

I see, so this explains why in `vim`, there is also an infinite delay, but hitting `<esc>` twice allows leaving insert mode. The default `maptimeout` for `screen` is 300ms, the default `escape-time` for `tmux` is 500ms. How does using them together result in the `<esc>` key never being sent until something else is sent too? 10 seconds seems like a very reasonable time to wait, but even if I wait _10 minutes_ (with either editor), the `<esc>` key is never received until something else is sent too. So not a bug with `kak`, but curious why these short delays add up to infinity, somehow.

**Comment by Screwtapello** [comment] 2020-07-10 13:20
I do not know, I've never seen that exact behaviour before.

Some wild-ass guesses:

- something somewhere is set to a 0ms timeout, which it interprets as "wait forever"
- some piece of networking equipment between you and the server tries to coalesce "too small" TCP packets to save bandwidth

If you run `cat` in a terminal and press Esc, it should immediately echo back `^[`. You might want to try running that locally, then inside screen on your local computer, then inside screen and ssh to the remote server, then in screen, ssh, and tmux on the remote server, and see if you can figure out which component of the system is introducing this behaviour.

**Comment by tino415** [comment] 2021-09-18 16:58
I have similiar problem on mac osx big sur  + alacrity + gnu screen when I tried 
```
buffer *debug*
set-option buffer debug keys
```
Then escape does nothing but when I press esc second time I got two escapes:
```
Client 'client0' got key '<esc>'
Client 'client0' got key '<esc>'
```
When I run kakoune without `GNU Screen` I got normal behaviour, when I tried to `cat` in GNU Screen I got `^[` when I pressed `<esc>`. In both situations I also tried to `Ctrl + [`. Also when I pressed esc and then any cahracter I got response like alt + something, aka `ESC + a` is `<a-a>`

**Comment by Screwtapello** [comment] 2021-09-18 23:36
That sounds like the same timeout behaviour already described. Try setting the Screen input timeout to zero (I'm not familiar with Screen, so I'm not sure what that setting would be called or how to set it).

**Comment by tino415** [comment] 2021-09-19 06:15
I tried `maptimeout 5` which is recommended but still I got esc in kakoune only on second press, on the other hand `esc + any key` return `alt + any key`, but when I try `cat`, I got `^[` instantly, gnu screen must somehow modifing imput so kakoune is thinking it is getting something else than when it is not running throught screen, for now I solved it by remaping `esc` to `ctrl + e`

**Comment by SeerLite** [comment] 2021-09-20 23:35
Can reproduce with `maptimeout 0` in `.screenrc` using `kak -n`. Tested on both Alacritty and st.

It starts working normally after setting `ui_options terminal_enable_mouse=false`. I noticed this because it worked normally with my user configuration, but not with `kak -n`. @tino415 You could use that as a workaround in the meantime.

I'm on a39516e0dd6a2dec8d6fcf35371f540d7c0a7a93. Not sure if this is a Kakoune issue or a screen issue.

**Comment by bitonic** [comment] 2021-10-10 08:06
@SeerLite I just tried with `ui_options terminal_enable_mouse=false` and I still need to press `ESC` twice. Is that the only configuration you needed to set?
