### ISSUE TITLE
Bad character display - Nix pkg manager

### ISSUE THREAD

**Issue by RuiRojo** [mawww/kakoune#2471] opened 2018-10-03 10:10 UTC
### Steps

Install Kakoune through Nix package manager, and run.

I've tried it with

* Nixpkgs current commit: af51ecee24288a9f3b5a671a5fa0b4ad5a823c35  (and other commits of the last weeks). This means Kakoune@v2018.09.04 I think.

* Gnome-terminal, mlterm, lilyterm

* Tried it from NixOS from 2 different PCs, and from those PCs through SSH to a Scientific Linux server on which Kakone was installed through the Nix package manager

* Shell: `zsh` (if I run `bash` from a terminal and then `kak`, the problem is still there)

### Outcome

![scr](https://user-images.githubusercontent.com/1438496/46404343-41455380-c6db-11e8-9f93-6f4e81bbf360.png)

Vim works perfectly well

The output of `locale -a && locale`, as requested on the IRC channel, is [pasted here](https://pastebin.com/XdhYrdct)

#### Failed tests

I've added `doCheck = true`  to the Nix derivation so tests are run. The results say that there are 4 failures among 353 tests. If I interpret the output correctly, the tests that fail are:

* vertical movements
* unicode
* 638-highlight-codepoint-with-bracket
* 811-double-width-codepoints

### Expected

Nice accents and beautiful clippy

**Comment by alexherbo2** [comment] 2018-10-04 20:48
@RuiRojo Have you solved your issue?

I’m on [NixOS] as well ([nixos-unstable]) with [latest].

[NixOS]: https://nixos.org
[nixos-unstable]: https://nixos.org/channels/nixos-unstable (nixos-19.03)
[latest]: https://github.com/mawww/kakoune/commit/fd00776012dd7a7cbd1d81c890486fdfd65bcbfd

**Comment by RuiRojo** [comment] 2018-10-04 20:55
@alexherbo2 No,a nd I didn't have time yet to continue.

On one of my machines, the issue got fixed after following a recommendation of [NixOS/nixpkgs#38991](https://github.com/NixOS/nixpkgs/issues/38991), of adding `glibc = {locales = true;};` to `~/.nixpkgs/config.nix`. This triggered a long recompilation of stuff, and in the end, `file -d /run/current-system/sw/lib/locale` showed it was aiming to "...glibc-locales-2.23/lib/locale", and the issue was suddenly fixed.

However, this same thing didn't fix it on another machine, also with NixOS, but with an older `nixos-rebuild`. In both I'm installing the latest kakoune, but with `nix-env`, not on `configuration.nix`. In the machine that still doesn't work, I can't really update NixOS easily because something breaks with my nvidia card.

On the server running scientific linux, it also didn't get fixed just by adding that line.

But, it sounds like it's related to that issue [NixOS/nixpkgs#38991](https://github.com/NixOS/nixpkgs/issues/38991) and I haven't tried all the stuff that people say over there.

**Comment by MarSoft** [comment] 2019-04-28 19:58
Cannot reproduce on current NixOS 19.03, kakoune version 2018-08-05.

**Comment by makmm** [comment] 2019-08-02 13:36
Reproduced on Debian sid on top of [Crouton](https://github.com/dnschneid/crouton). Compiled with Ubuntu steps.

**Comment by lenormf** [comment] 2020-03-14 11:54
Looks like a locale-related issue, could we close this?

**Comment by v0idifier** [comment] 2020-03-14 21:56
ah i had the same issue in a completely different platform, generating locales worked, so +1

**Closed** 2020-03-15 23:57 UTC
