### ISSUE TITLE
Remove `.` and `..` candidates from file-name completion

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#1756] opened 2017-12-08 10:48 UTC

**Comment by lenormf** [comment] 2017-12-08 11:05
Dupe of #1755?

**Comment by mawww** [comment] 2017-12-09 11:10
If thats in insert mode, I just fixed it, if it was the same a #1755, its probably the same problem with your ignored_files regex.

**Comment by lenormf** [comment] 2017-12-23 07:04
Since dot files are normally hidden in command mode, I don't think we need to go the extra mile and specifically exclude `.` and `..` from completion.

**Comment by mawww** [comment] 2017-12-28 22:39
Yeah, we have `ignored_files` for that.

**Closed by mawww** 2017-12-28 22:39 UTC
