### ISSUE TITLE
Numeric (regex group) registers are cleared by buffer changes

### ISSUE THREAD

**Issue by Screwtapello** [mawww/kakoune#3544] opened 2020-06-04 14:54 UTC
### Steps 

```
kak -n -e 'edit -scratch; execute-keys ixax<esc> /(a)<ret> x c x<c-r>1x<esc>'
```

Written out longhand:

- Launch Kakoune without any custom configuration
- Create a new scratch buffer
- Insert the text `xax`
- Search the buffer for `a`, storing that match into the regex group 1
- Select the entire line containing the match, then delete it and enter insert mode
- Type an `x`, then the contents of regex group 1, then another `x`

### Outcome 

The buffer contains `xx`; inserting the contents of regex group 1 inserts an empty string, not the text that was matched.

### Expected 

The buffer contains `xax`, as it did originally.

### Notes

- This change was introduced by commit 63371da
- This bug does not manifest if:
    - you just change the match instead of the entire line
    - you modify the selection with `l` instead of `x`
    - you use `a` instead of `c`
- That is, the bug seems to require deleting the context of the match, not just the match itself
- This was [originally reported](https://gitlab.com/Screwtapello/kakoune-inc-dec/-/issues/7) as a bug in my "kakoune-inc-dec" plugin by Charles Gueunet.

**Comment by nonumeros** [comment] 2020-06-11 12:22
If the group is supposed to be a numeric character, say `1`, then no, the matched value is not being returned . I agree with you there. But if the numeric character is assigned to `0`, I don't see any difference here. And either the label you assigned to the issue is wrong or I'm wrong. Even compiling with 83cdaee0 I couldn't see any discernible difference between the two commits.

Yes. If,  say for example, `(a)` is used, then it returns what you expected. As it is, is pretty much behaving as if I were searching for`[a]` rather than the former from your non-working example. 

As always, thanks for breaking it down nicely.

**Comment by lenormf** [comment] 2020-06-11 12:37
Was this not fixed by 66f15cf4ad8b0127f93503cad41d570a7c9f5d72?

**Comment by nonumeros** [comment] 2020-06-12 08:30
i can care less about the emojis. @krobelus what do you have for breakfast?… if it's fixed as you presumably consider it so, then perl rregex backreferences must be somehow specified on the docs. I think the issue @Screwtapello  brought up is still valid.

**Comment by mawww** [comment] 2020-06-25 11:27
I belive thats fixed, re-open if not

**Closed by mawww** 2020-06-25 11:27 UTC
Labels: bug
