### ISSUE TITLE
Fzf Empty File List

### ISSUE THREAD

**Issue by dbettin** [mawww/kakoune#1348] opened 2017-05-05 05:28 UTC
Issue
======
Using the standard fzf-file scripts and the latest kakoune bits,  kakoune shows an emtpy list when using fzf-file.

Additional Information
-------
* Fzf works just fine in the shell via both fzf and fzf-tmux.  
* fzf version is `0.16.7`
* It is a recent breakage; if I git reset to the following sha (https://github.com/mawww/kakoune/commit/80dd9ec4cb68669df4688c621486a27dd9b33548) it works fine.

**Comment by lenormf** [comment] 2017-05-05 07:15
There is no standard `fzf` support script, you might be creating the issue in the wrong repository. Where did you get that script from exactly? Have you checked the `*debug*` buffer for any error message?

**Comment by Delapouite** [comment] 2017-05-05 07:31
There are indeed a few fzf scripts on the wiki : https://github.com/mawww/kakoune/wiki/Fuzzy-finder

**Comment by dbettin** [comment] 2017-05-05 14:56
I am using the scripts from the wiki. This is not a script issue, as they work on the older versions of kakoune. It is broken with the HEAD version of kakoune and there is no *debug* info, it just returns an empty list.

**Comment by Delapouite** [comment] 2017-05-17 15:05
I can confirm it's not working anymore. Seems like an issue with `$FZF_DEFAULT_COMMAND`.
A temp workaround is to specify what you pass as `stdin`. Default command use `find`, but here's one version with `ripgrep` if you have it:
```
def -docstring 'invoke fzf to open a file' \
fzf-file %{ %sh{
  if [ -z "$TMUX" ]; then
    echo echo only works inside tmux
  else
    FILE=$(rg --files --hidden | fzf-tmux -d 15 --preview="highlight --force -O ansi {} | head -n 30" --preview-window=right:50%)
    if [ -n "$FILE" ]; then
      echo "eval -client '$kak_client' 'edit ${FILE}'" | kak -p ${kak_session}
    fi
  fi
}}
```

**Comment by lenormf** [comment] 2017-05-24 14:25
This issue was caused by 52ffa98787dccc0ecd02b81b43df715dd9b6e9fe, which closes the process' `stdin`, making it impossible for `fzf-tmux` to access the client's standard input.

The following is an updated (and POSIX) version of the script on the wiki that should work just as well:

```
def -docstring 'invoke fzf to open a file' \
  fzf-file %{ %sh{
    if [ -z "$TMUX" ]; then
      echo echo only works inside tmux
    else
      FILE=$(ls -1 | fzf-tmux -d 15)
      if [ -n "$FILE" ]; then
        printf 'eval -client %%{%s} edit %%{%s}\n' "${kak_client}" "${FILE}" | kak -p "${kak_session}"
      fi
    fi
} }
```

**Comment by mawww** [comment] 2017-06-03 17:19
Was that fixed on the wiki ? Can we close this ?

**Comment by lenormf** [comment] 2017-06-05 15:40
I fixed the wiki, this issue can be closed.

**Closed** 2017-06-08 08:57 UTC
