### ISSUE TITLE
Use $XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#3019] opened 2019-07-12 19:12 UTC
### Steps

1. Open a Kakoune session (perhaps with a wrapper that chooses the session name based on tmux window name).
2. Experience power failure
3. Power server back on and log back into server
4. Open a Kakoune session

### Outcome

"Socket already in use"

`kak -clear` will clean it up.

### Expected

Socket doesn't exist, because it was stored in `$XDG_RUNTIME_DIR`, which intentionally does not persist across reboots.  If the variable is set... probably fine to default to the current mechanism when not set (it isn't set on Mac OS).

**Comment by lenormf** [comment] 2019-07-13 10:20
The sockets are stored in `$TMPDIR` which by convention does not persist across reboots. Report the bug to your distribution.

**Comment by eraserhd** [comment] 2019-07-16 14:21
`/tmp`, according to POSIX:

> A directory made available for applications that need a place to create temporary files. Applications shall be allowed to create files in this directory, but shall not assume that such files are preserved between invocations of the application.

So, POSIX doesn't *require* this.

I'm on NixOS, and there are configuration options to clean on boot, or to mount it on tmpfs, but these are not default.  I'm going to set clean on boot, but I still think we should use `$XDG_RUNTIME_DIR`.

**Comment by lenormf** [comment] 2019-07-16 18:21
I think your issue is that the dead session isn't seamlessly recovered/overridden - in the end creating sockets in `$XDG_RUNTIME_DIR` will result in the same outcome when the server crashes unexpectedly at runtime (you'll have to call `kak -clear`) as when they're created in `$TMPDIR`.

**Comment by eraserhd** [comment] 2019-07-16 19:05
According to [the spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), `$XDG_RUNTIME_DIR`:

> The lifetime of the directory MUST be bound to the user being logged in. It MUST be created when the user first logs in and if the user fully logs out the directory MUST be removed. If the user logs in more than once he should get pointed to the same directory, and it is mandatory that the directory continues to exist from his first login to his last logout on the system, and not removed in between. Files in the directory MUST not survive reboot or a full logout/login cycle.

In NixOS, it's a tmpfs mount, so this works correctly.

**Comment by Screwtapello** [comment] 2019-07-16 23:19
Using `$XDG_RUNTIME_DIR` means that Kakoune sessions are automatically cleaned up after a reboot or a login-session crash, but Kakoune crashes still cause problems.

Using `$TMPDIR` means that Kakoune sessions are never automatically cleaned up.

If Kakoune automatically ran the equivalent of `-clear` each time it started, sessions would always be automatically cleaned up. I assume there's a good reason why Kakoune shouldn't `-clear` automatically, but I can't think of it immediately.

If the majority of dead sessions come from Kakoune crashes, it doesn't make sense to put the effort into using `$XDG_RUNTIME_DIR` yet, because people will still have to learn to use `kak -clear` occasionally. On the other hand, if the majority of dead sessions come from system reboots and crashes, it makes more sense to use `$XDG_RUNTIME_DIR` because then `kak -clear` becomes less important.

**Comment by lenormf** [comment] 2019-07-17 06:38
I think sessions are not recovered seamlessly to make sure the user notices something went wrong, and potentially attach a debugger to the server if it's still alive but accepting new clients.

**Comment by mawww** [comment] 2019-07-21 02:47
We dont clear sessions automatically because I consider `kak -l` and `kak -clear` ugly hacks (but pragmatic ones). I dont want to link the default kakoune behaviour with those.

Regarding XDG_RUNTIME_DIR, I think it would make sense to use it for session sockets, as we already try to follow XDG for the configuration file location.

One potential issue though is that if I understand XDG_RUNTIME_DIR correctly, a user that is logged in multiple times simulateneously might use two different directories for his different login sessions, which means sharing Kakoune sessions between those would be more painful. Is that correct ?

**Comment by eraserhd** [comment] 2019-07-21 05:10
Spec says:

> If the user logs in more than once he should get pointed to the same
directory, and it is mandatory that the directory continues to exist from
his first login to his last logout on the system, and not removed in
between.

This os how it works on NixOS.

**Comment by lenormf** [comment] 2019-07-21 07:39
>I dont want to link the default kakoune behaviour with those.

So, EWONTFIX? Changing where the sockets are stored won't address the expected behaviour described in this issue :/

**Comment by mawww** [comment] 2019-07-21 10:34
My current understanding is that it will fix the issue, as the directory is going to be empty after reboot.

Regardless of that issue, using  `$XDG_RUNTIME_DIR` would be more respectful of the XDG spec, which we kind-of follow for configuration. Howerver it would break one (rare) use case, which is giving access to the socket to another user so that they can connect to the session, as XDG_RUNTIME_DIR is mantated to be 0700.

**Comment by lenormf** [comment] 2019-07-21 10:52
It seems rather specific to want the socket to be removed only in the event that the system is brought down unexpectedly, I was under the impression that the issue was about any time the server stops serving requests on the socket (for any reason).

**Comment by eraserhd** [comment] 2019-07-21 17:43
If I’m honest, I already had an agenda for $XDG_RUNTIME_DIR, and just filed
this issue when it bit me.  While I still figure using it is a good thing,
my real reason to want it has to do with making my experimental 9p and
fs-registers patches work nicely, and concluding from those experiences the
abstract idea that Kakoune would work better if it honored this piece of
the standard.

So I wasn’t really worried about the particular case, just slightly caremad?

**Comment by lenormf** [comment] 2019-07-22 06:22
What default path should be used, if that variable isn't defined? `/run/user/$UID/kakoune`?

**Comment by mawww** [comment] 2019-07-22 06:49
Good question, seems the spec does not give lots of guidance on that. Thats what XDG_RUNTIME_DIR is pointing to here, and where i3 seems to be putting its socket.

**Comment by Screwtapello** [comment] 2019-07-22 07:13
> If $XDG_RUNTIME_DIR is not set applications should fall back to a replacement directory with similar capabilities and print a warning message.

Any distro modern enough to have a `/run` directory almost certainly already sets `$XDG_RUNTIME_DIR`, so making `/run/user` the fallback probably isn't helpful. The real fallback would be what Kakoune does at the moment - create a predictably-named socket in a world-writable location and hope that nobody will try to race the socket creation to do anything underhanded.

**Comment by lenormf** [comment] 2019-07-22 07:53
Both paths would be equally unpredictable, since their root depend on the environment:

```
${TMPDIR:-/tmp}/kakoune/$USER/$session
```

versus

```
${XDG_RUNTIME_DIR:-/run/user/$UID}/kakoune/$USER/$session
```

It would also be bad to have two different sets of directory permissions depending on whether an environment variable is set.

Here's a patch that implements the changes:

```diff
diff --git a/src/file.cc b/src/file.cc
index c1f5bb26..059300a8 100644
--- a/src/file.cc
+++ b/src/file.cc
@@ -130,6 +130,15 @@ String compact_path(StringView filename)
     return filename.str();
 }
 
+StringView runtimedir()
+{
+    StringView rtdir = getenv("XDG_RUNTIME_DIR");
+    if (not rtdir.empty())
+        return rtdir.back() == '/' ? rtdir.substr(0_byte, rtdir.length()-1)
+                                    : rtdir;
+    return format("/run/user/{}", geteuid());
+}
+
 StringView tmpdir()
 {
     StringView tmpdir = getenv("TMPDIR");
diff --git a/src/file.hh b/src/file.hh
index 5264616b..25e0e030 100644
--- a/src/file.hh
+++ b/src/file.hh
@@ -26,6 +26,7 @@ String parse_filename(StringView filename, StringView buf_dir = {});
 String real_path(StringView filename);
 String compact_path(StringView filename);
 
+StringView runtimedir();
 StringView tmpdir();
 StringView homedir();
 
diff --git a/src/main.cc b/src/main.cc
index 620a3da8..72eb60f2 100644
--- a/src/main.cc
+++ b/src/main.cc
@@ -1018,8 +1018,8 @@ int main(int argc, char* argv[])
         if (list_sessions or clear_sessions)
         {
             const String username = get_user_name();
-            const StringView tmp_dir = tmpdir();
-            for (auto& session : list_files(format("{}/kakoune/{}/", tmp_dir,
+            const StringView rtdir = runtimedir();
+            for (auto& session : list_files(format("{}/kakoune/{}/", rtdir,
                                                    username)))
             {
                 const bool valid = check_session(session);
@@ -1028,7 +1028,7 @@ int main(int argc, char* argv[])
                 if (not valid and clear_sessions)
                 {
                     char socket_file[128];
-                    format_to(socket_file, "{}/kakoune/{}/{}", tmp_dir,
+                    format_to(socket_file, "{}/kakoune/{}/{}", rtdir,
                               username, session);
                     unlink(socket_file);
                 }
diff --git a/src/remote.cc b/src/remote.cc
index 83fc8adc..b4efeff8 100644
--- a/src/remote.cc
+++ b/src/remote.cc
@@ -545,9 +545,9 @@ static sockaddr_un session_addr(StringView session)
     if (slash_count > 1)
         throw runtime_error{"session names are either <user>/<name> or <name>"};
     else if (slash_count == 1)
-        format_to(addr.sun_path, "{}/kakoune/{}", tmpdir(), session);
+        format_to(addr.sun_path, "{}/kakoune/{}", runtimedir(), session);
     else
-        format_to(addr.sun_path, "{}/kakoune/{}/{}", tmpdir(),
+        format_to(addr.sun_path, "{}/kakoune/{}/{}", runtimedir(),
                   get_user_name(), session);
     return addr;
 }
@@ -785,7 +785,7 @@ Server::Server(String session_name)
     sockaddr_un addr = session_addr(m_session);
 
     // set sticky bit on the shared kakoune directory
-    make_directory(format("{}/kakoune", tmpdir()), 01777);
+    make_directory(format("{}/kakoune", runtimedir()), 01777);
     make_directory(split_path(addr.sun_path).first, 0711);
 
     // Do not give any access to the socket to other users by default
@@ -819,9 +819,9 @@ bool Server::rename_session(StringView name)
     if (not all_of(name, is_identifier))
         throw runtime_error{format("invalid session name: '{}'", name)};
 
-    String old_socket_file = format("{}/kakoune/{}/{}", tmpdir(),
+    String old_socket_file = format("{}/kakoune/{}/{}", runtimedir(),
                                     get_user_name(), m_session);
-    String new_socket_file = format("{}/kakoune/{}/{}", tmpdir(),
+    String new_socket_file = format("{}/kakoune/{}/{}", runtimedir(),
                                     get_user_name(), name);
 
     if (file_exists(new_socket_file))
@@ -838,7 +838,7 @@ void Server::close_session(bool do_unlink)
 {
     if (do_unlink)
     {
-        String socket_file = format("{}/kakoune/{}/{}", tmpdir(),
+        String socket_file = format("{}/kakoune/{}/{}", runtimedir(),
                                     get_user_name(), m_session);
         unlink(socket_file.c_str());
     }
```

**Comment by eraserhd** [comment] 2019-07-29 14:30
Having `$USER` in `XDG_RUNTIME_DIR` is redundant.  Also, falling back to `/run/user/$UID` could be problematic, since if `XDG_RUNTIME_DIR` is not set, there's no telling whether `/run/user` exists - as @Screwtapello says.

It needs to use `$XDG_RUNTIME_DIR/kakoune/$SESSION` if `XDG_RUNTIME_DIR` is set (and not worry about permissions), and fall back to `/tmp/kakoune/$USER/$SESSSION` if $XDG_RUNTIME_DIR is not set.

**Closed** 2019-08-11 09:19 UTC

**Comment by lenormf** [comment] 2019-08-11 10:07
How about editing the changelog to notify users that sessions are stored in a separate place? They will also need to re-open their long-standing sessions, to allow spawning new clients if they simply upgrade the package.
