### ISSUE TITLE
What do you use kakoune for?

### ISSUE THREAD

**Issue by AnthonyJacob** [mawww/kakoune#1283] opened 2017-03-17 18:59 UTC
Kakoune describes its purpose as text editor. Yet its vim similar design targets very specific group of people. The page also states kakoune is no IDE, which I interpret as I won't get any better support for programming but syntax highlighting.

At this point I am asking myself what is this tool going to be used for, because I as programmer (spacemacs with vim keybindings is currently my IDE) see no utilization for it although I loved playing with it and exploring it.

So what do **you** use kakoune for?

**Comment by alexherbo2** [comment] 2017-03-17 19:49
I use it as a code editor and general text editor.

What do you miss from Kakoune?

**Comment by alexherbo2** [comment] 2017-03-17 20:00
Does [Limited scope][] and [Composability][] from [Kakoune design][] help?

[Kakoune design]: https://github.com/mawww/kakoune/blob/master/doc/design.asciidoc
[Limited scope]: https://github.com/mawww/kakoune/blob/master/doc/design.asciidoc#limited-scope
[Composability]: https://github.com/mawww/kakoune/blob/master/doc/design.asciidoc#composability

**Comment by ekie** [comment] 2017-03-18 00:23
hej,

those documents alex is linking hold valueable information to grasp the design philosophy and motivation behind kakoune. the no in "no IDE" does not mean u cannot use kakoune as one. kakoune is not shipping all batteries included, but does not fall short with options to extend its behaviour to fit your needs.
the editor is evolving and depends on peoples input and their use cases, and it would be nice if you can identify some limitations you hit.

to answer your question, my use for kakoune:
* programming
* navigating and exploring code
* replaced the gitworkflow from terminal
* mail
* task management
* technical writing

**Comment by AnthonyJacob** [comment] 2017-03-20 15:13
What I am missing for programming is some error highlighting and more sophisticated auto completion.

**Comment by dumblob** [comment] 2017-03-20 17:35
I sort of use kak from time to time for playing with it and testing it. Why not anything else (i.e. serious)? Because I'm too lazy and need e.g. the kakdiff https://github.com/mawww/kakoune/issues/153 functionality.

**Comment by ekie** [comment] 2017-03-21 00:35
@AnthonyJacob kakoune ships with https://github.com/mawww/kakoune/blob/b9317ba38c3e8f2bc4196705d65bbc8a8ef8dbf4/rc/base/lint.kak and can be adapted to diverging tooling. i guess it depends on the particular programming language and if u can pinpoint the shortcoming there might be an easy solution. moreover where does the autocomplete system out of the box needs some refining?

**Comment by mawww** [comment] 2017-03-21 17:38
When I wrote that Kakoune is not an IDE, it means Kakoune wont have a builtin project management, build system, code completion...

That does not mean Kakoune wont support these features, it means it will provide them through interaction with external tools. Kakoune does not provide a project management and build system, but you can easily use `make` from inside Kakoune, get the result in a buffer and auto jump to errors. the bundled `make.kak` script does exactly that. Similarly, Kakoune wont implement built-in logic for code parsing and completion, but provides all the needed tools to intergrate with existing code completion tools and display a completion menu. `clang.kak` provides that for C/C++, `jedi.kak` does it for python...

`git-tools.kak` provides git integration for use from within the editor as well.

I use Kakoune myself at work (I am on break at the moment, but I work in the video game industry as a game programmer), so mostly working on C++ codebases. I also use it for every other text editing needs, like mails, or document writing.

**Comment by pickfire** [comment] 2017-03-25 10:04
> replaced the gitworkflow from terminal
> mail
> task management

@ekie Wow, can you please clarify that?

Even though I am thinking of switching away from neovim (probably vis or kak) and had switched to dvp (dvorak for programmers) layout, kakoune looks fine with it.

**Comment by mawww** [comment] 2017-04-10 20:43
Seems this is not a bug or feature request, and the discussion is finished, so I'll close it.

**Closed by mawww** 2017-04-10 20:43 UTC

**Comment by FranzSkuffka** [comment] 2017-12-23 15:55
I am using kakoune for more than a year now and it's probably one of the most valuable tools in my chain. I switched over from vim because vim was too reliant on huge configurations to be efficient. I combine kakoune with https://github.com/clvv/fasd. Possibly the fastest way to edit an arbitrary text file in your projects.
