### ISSUE TITLE
alt→ doesn't work in Terminal.app

### ISSUE THREAD

**Issue by kballard** [mawww/kakoune#997] opened 2016-12-15 01:50 UTC
Pressing `alt→` in Terminal.app instead behaves like `alt-f`. This is because the default keyboard mapping is `\033f`, which is apparently the same thing as `alt-f`. I'm not sure what the appropriate thing to do here is, beyond providing some other shortcut for the same behavior.

**Comment by mawww** [comment] 2016-12-16 00:10
Yep, kakoune will interpret `<esc>f` as `<a-f>`, using a timeout to distinguish plain `<esc>` from `<a-something>`. I dont know what we can do there, its a terminal input limitation, eventual GUI will not have that problem.

**Comment by kballard** [comment] 2016-12-16 06:39
As I suggested, perhaps you should provide an alternative keyboard shortcut as a predefined alias. That way Terminal.app users don't all have to rebind it themselves.

**Comment by lenormf** [comment] 2016-12-16 06:58
The keyboard is already pretty full as it is, there is not a lot of room for such configuration-dependant hacks.

**Comment by pauldub** [comment] 2016-12-16 09:05
Also this is really a problem with Terminal.app handling of alt (also known as meta) which affects emacs users heavily for example. I do not think it is possible to setup Terminal.app to handle the alt key correctly in the same way as ITerm2.

**Comment by kballard** [comment] 2016-12-16 23:19
What you quoted is something different. Terminal.app lets you either use Option as the Meta key, or use it like it works in all other apps for entering text (e.g. ⌥e produces the ´ accent over the next key).

This is completely different than the problem I'm describing, which is the default keybinding of ⌥→ is the same as ⌥F. I'm guessing this keybinding exists the way it does so that way users pressing ⌥→ and ⌥← have their selection move by words in anything using conventional line editing (including shells). It's certainly possible for users to rebind this, but it's probably safe to assume that very few people have rebound those keys in Terminal.app.

**Comment by rawaludin** [comment] 2016-12-17 05:22
I'm having same problem. Using iTerm2, alt+h not bring me to first character on line. Other key combination using alt is not working too.

Here is my iterm configuration
<img width="665" alt="screen shot 2016-12-17 at 12 21 23 pm" src="https://cloud.githubusercontent.com/assets/1274849/21284611/5e5d5b48-c453-11e6-87cc-5b6091c8a1f2.png">

**Comment by casimir** [comment] 2016-12-19 12:58
I use this configuration (see _left option key_). That way the left alt key works `<alt-h>` and the right alt key allow international keyboard combination like `<alt-e>e` for `é`.

<img width="680" alt="screen shot 2016-12-19 at 13 57 41" src="https://cloud.githubusercontent.com/assets/879004/21313606/24946810-c5f3-11e6-86a3-06bace26e949.png">

**Comment by lenormf** [comment] 2016-12-19 13:01
@casimir maybe you could grab your configuration file (with the bindings in it), as create a PR that adds it to `contrib` ? As far as I know `iterm2` is popular, so most mac users could just copy/paste the key combinations from your config.

**Comment by casimir** [comment] 2016-12-19 13:05
Well, this is the default mapping, the only thing I did was checking a radio button (`+Esc`). Maybe an FAQ entry would help though.

**Comment by lenormf** [comment] 2016-12-19 13:13
A FAQ entry would be good indeed.

**Comment by kballard** [comment] 2016-12-19 18:58
Again, whether option behaves as meta or as Mac-native option is *completely unrelated* to this PR.

**Comment by mawww** [comment] 2017-01-08 11:22
So, If I did not miss anything, this is a duplicate of #1016.

**Closed by mawww** 2017-01-08 11:22 UTC
