### ISSUE TITLE
ask before overwitting a file with `:w`

### ISSUE THREAD

**Issue by sucrecacao** [mawww/kakoune#3717] opened 2020-09-06 14:31 UTC
### Feature 

When executing the command `:w foo.txt`, if `foo.txt` already exist ask for confirmation before overwriting it .

### Usecase 
Prevent lost of data.

**Comment by krobelus** [comment] 2020-09-06 15:07
Duplicate of #3587

**Closed** 2020-10-01 01:05 UTC
Labels: feature request
