### ISSUE TITLE
All the colorscheme's colors are darker than what they should be 

### ISSUE THREAD

**Issue by snakedye** [mawww/kakoune#4254] opened 2021-07-06 20:06 UTC
### Steps 
https://gitlab.com/snakedye/wlr_config/-/blob/master/kak/.config/kak/kakrc
https://gitlab.com/snakedye/wlr_config/-/blob/master/kak/.config/kak/colors/chocolate.kak

### Outcome 
![image](https://user-images.githubusercontent.com/49378990/124660359-1a13a600-de74-11eb-98a3-f2556b9bce88.png)
![image](https://user-images.githubusercontent.com/49378990/124660400-27c92b80-de74-11eb-8436-a05dd948b941.png)

### Expected 
Colors should match.

**Comment by caksoylar** [comment] 2021-07-06 21:12
I also did some testing just now and I can confirm the master branch colors are 1 point darker in all three RGB values than the specification, unless it is `rgb:000000` or `rgb:FFFFFF` in which case it is equal. The terminal output is matching, so it is Kakoune-related. `builtin-terminal-ui` works as expected as well.

**Comment by mawww** [comment] 2021-07-09 01:16
Hello,

Took a look, some colors are off, others are not,  I suspect the issue is how ncurses handles colors by using a 0-1000 range.

Kakoune converts from 0-255 to 0-1000 by doing `c -> c * 1000 / 255` which I think is correct (it will project 0 to 0 and 255 to 1000, and is linear in between). But because 1000 is not a multiple of 255 there might be some rounding off issues when ncurses converts back from 0-1000 to 0-255.

I intend to merge builtin-terminal-ui soon with will fix this.

**Comment by mawww** [comment] 2021-09-25 23:45
This should be fixed now that we merged the builtin-terminal-ui

**Closed by mawww** 2021-09-25 23:45 UTC
Labels: bug
