### ISSUE TITLE
gk jump in man.kak does nothing

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1073] opened 2016-12-26 17:09 UTC
Line 39 in `rc/core/man.kak` ends with `gk`:

    exec '%|cat<space>${colout}<ret>gk'
    
But this is run in a `WinResize` hook, which are run in  disposable contexts. Hence the `gk` does nothing. This makes the cursor stay at the end of the manual after a resize, and makes it very difficult to move the cursor to a good location at all after a window resize.

**Comment by mawww** [comment] 2017-01-03 18:49
Yeah, this fails with WinResize, the best would probably be to fix #312 so that piping would detect actual changes to the buffer, hopefully preserving the selection at the correct position.

**Comment by lenormf** [comment] 2018-12-16 08:01
Can't reproduce the issue, the cursor remains in the same position upon resizing the window. Close?

**Comment by mawww** [comment] 2020-05-29 03:47
This does not seem relevant anymore, closing.

**Closed by mawww** 2020-05-29 03:47 UTC
