### ISSUE TITLE
Begin versioning/releasing kakoune?

### ISSUE THREAD

**Issue by jjthrash** [mawww/kakoune#89] opened 2014-04-05 18:48 UTC
I'm working on a homebrew recipe to make it easy to to install on OSX. (Try `brew install https://raw.githubusercontent.com/jjthrash/homebrew/master/Library/Formula/kakoune.rb`)

However, I had to make up a version number, 0.1, since kakoune doesn't have one. It would be handy if you could make an "official" release version.

However, I can also just change the recipe to version the installs based on date of latest commit for the build, e.g. 20140403 for the build corresponding to the recipe above.

**Comment by OJFord** [comment] 2016-12-17 21:29
@mawww @jjthrash The `head-only` repo is going (Homebrew/homebrew-head-only#186); maintainer asking about it in #315 (which is a duplicate of this really, in title at least).

**Comment by lenormf** [comment] 2016-12-18 07:53
Nothing indicates that the repository is going to be removed any time soon, there's still time. The recipe is outdated though, c.f. #977.

**Comment by lenormf** [comment] 2017-05-01 08:25
Relevant to this issue: http://semver.org/

**Comment by alyssais** [comment] 2017-08-11 14:56
Homebrew maintainer here. To my knowledge, we won't be taking any more head-only formulae and that repo has been put into read-only mode. If you're not ready to commit to versioned releases, you could put the formula in your own [Homebrew tap](https://docs.brew.sh/brew-tap.html) (basically just a dedicated Git repo) so your users can still get updates through Homebrew, and when the formula gets into Homebrew core those installations can be seamlessly migrated. We do recommend moving to versioned releases as soon as possible though, because it provides a much better experience when using a package manager.

Let me know if I can help at all! :)

**Comment by jjthrash** [comment] 2017-08-11 15:12
@alyssais Thanks for the heads-up. Homebrew user here, and I'm fine using a tap. @mawww If you want me to set up a tap, let me know.

**Comment by Delapouite** [comment] 2018-04-19 09:32
https://github.com/mawww/kakoune/releases/tag/v2018.04.13

**Comment by alfiepates** [comment] 2018-04-19 10:05
<3

Thanks, @mawww!

**Comment by mawww** [comment] 2018-04-20 00:45
You are welcome.

**Closed by mawww** 2018-04-20 00:45 UTC
