### ISSUE TITLE
Issue installing through Homebrew on Mac OS X

### ISSUE THREAD

**Issue by pusewicz** [mawww/kakoune#579] opened 2016-02-04 11:30 UTC
Installing does not work on OS X El Capitan:

```
######################################################################## 100.0%
==> Cloning https://github.com/mawww/kakoune.git
Updating /Library/Caches/Homebrew/kakoune--git
==> Checking out branch master
==> make install PREFIX=/usr/local/Cellar/kakoune/HEAD
Last 15 lines from /Users/piotr/Library/Logs/Homebrew/kakoune/01.make:
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .regex.debug.d -c -o .regex.debug.o regex.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .register_manager.debug.d -c -o .register_manager.debug.o register_manager.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .remote.debug.d -c -o .remote.debug.o remote.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .selection.debug.d -c -o .selection.debug.o selection.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .selectors.debug.d -c -o .selectors.debug.o selectors.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .shared_string.debug.d -c -o .shared_string.debug.o shared_string.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .shell_manager.debug.d -c -o .shell_manager.debug.o shell_manager.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .string.debug.d -c -o .string.debug.o string.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .unit_tests.debug.d -c -o .unit_tests.debug.o unit_tests.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .window.debug.d -c -o .window.debug.o window.cc
clang++ -DKAK_DEBUG -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -MD -MP -MF .word_db.debug.d -c -o .word_db.debug.o word_db.cc
a2x -f manpage ../doc/kakoune.1.txt
make: a2x: No such file or directory
make: *** [../doc/kakoune.1.gz] Error 1
make: *** Waiting for unfinished jobs....
```

Please let me know if you need more information, thanks!

**Comment by greduan** [comment] 2016-02-04 11:52
Probably has to do with the recent changes to the manpages stuff.

**Comment by lenormf** [comment] 2016-02-04 12:28
@pusewicz you need to install the `asciidoc` package, which should contain the `a2x.py` script.

**Comment by pusewicz** [comment] 2016-02-04 12:44
@lenormf I do have it! I think it's just given the wrong path for the file to process:

```
$ which a2x.py
/usr/local/bin/a2x.py
```

**Comment by lenormf** [comment] 2016-02-04 12:45
@pusewicz it will be fixed in #578, thanks for reporting the issue!

**Comment by jmelfi** [comment] 2016-02-04 16:30
@lenormf I was actually going to post this issue.  I have a2x referenced as `a2x` and `a2x.py` and the build still fails on OSX El Capitan.

I can run a2x from the command line with no issues.

**Comment by lenormf** [comment] 2016-02-06 08:38
@pusewicz @jmelfi I think the version of `make` that you are using does not use a `PATH` that includes the directory where `homebrew` has installed `a2x` (that's how I assume you've installed `asciidoc` and `a2x`, correct me if I'm wrong).

Could you please give me the output of the following commands, run in a shell ?

```
which a2x
which a2x.py
```
```
make -v
```
```
printf 'all:\n\techo $(shell which a2x)' | make -f -
printf 'all:\n\techo $(shell which a2x.py)' | make -f -
```
```
printf 'all:\n\techo $$PATH' | make -f -
```

**Comment by pusewicz** [comment] 2016-02-06 13:34
Here you go!

```
[piotr@Hiigara]  $ which a2x
/usr/local/bin/a2x
[piotr@Hiigara]  $ which a2x.py
/usr/local/bin/a2x.py
[piotr@Hiigara]  $ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
[piotr@Hiigara]  $ printf 'all:\n\techo $(shell which a2x)' | make -f -
echo /usr/local/bin/a2x
/usr/local/bin/a2x
[piotr@Hiigara]  $ printf 'all:\n\techo $(shell which a2x.py)' | make -f -
echo /usr/local/bin/a2x.py
/usr/local/bin/a2x.py
[piotr@Hiigara]  $ printf 'all:\n\techo $$PATH' | make -f -
echo $PATH
/Users/piotr/.rbenv/shims:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/Users/piotr/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:./bin:/usr/local/sbin:/Users/piotr/.rbenv/shims:/Users/piotr/bin:/Users/piotr/.8/bin:/Users/piotr/.8/bin
```

**Comment by lenormf** [comment] 2016-02-06 14:21
Can you modify `src/Makefile` after the repository has been cloned, and print the current PATH from it ? You could add `echo $$PATH` above line 82, I reckon the `make` call done when installing kakoune does not contain `/usr/local/bin`, although your shell apparently does.

**Comment by mawww** [comment] 2016-02-11 22:11
Should be fixed on current master.

**Closed by mawww** 2016-02-11 22:11 UTC

**Comment by jmelfi** [comment] 2016-02-11 22:58
@mawww I can confirm that this works now on Mac OSX with current master using Homebrew to install.  Thanks for the fix!

**Comment by mawww** [comment] 2016-02-11 23:31
nice, thanks for the confirmation

**Comment by cvlmtg** [comment] 2016-03-19 12:23
Hi, I'm having the same problem

```
$ brew install --with-docbook-xsl asciidoc
[...]
$ export XML_CATALOG_FILES=/usr/local/etc/xml/catalog
$ brew install --HEAD kakoune
==> Cloning https://github.com/mawww/kakoune.git
Updating /Library/Caches/Homebrew/kakoune--git
==> Checking out branch master
==> make install PREFIX=/usr/local/Cellar/kakoune/HEAD
Last 15 lines from /Users/matteo/Library/Logs/Homebrew/kakoune/01.make:
[...]
Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .word_db.debug.d -c -o .word_db.debug.o word_db.cc
a2x --no-xmllint -f manpage ../doc/kak.1.txt
make: a2x: No such file or directory
make: *** [../doc/kak.1.gz] Error 1
make: *** Waiting for unfinished jobs....
```

```
$ which a2x
/usr/local/bin/a2x
$ which a2x.py
/usr/local/bin/a2x.py
```

unfortunately it seems the fix made on Feb 11 doesn't work for me...

**Comment by supermarin** [comment] 2016-12-14 01:36
FWIW still happening on El Cap and Sierra

**Comment by lenormf** [comment] 2016-12-14 05:35
@supermarin the homebrew recipe has been updated, is it still failing when you try to install using it?

**Comment by supermarin** [comment] 2016-12-14 05:50
100% reproducible on 2 machines (el cap and sierra). 

```
~$ brew install kakoune --HEAD
==> Installing kakoune from homebrew/boneyard
==> Cloning https://github.com/mawww/kakoune.git
Updating /Users/marinusalj/Library/Caches/Homebrew/kakoune--git
==> Checking out branch master
==> make -C src install PREFIX=/usr/local/Cellar/kakoune/HEAD-8e351e8
Last 15 lines from /Users/marinusalj/Library/Logs/Homebrew/kakoune/01.make:
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .regex.debug.d -c -o .regex.debug.o regex.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .register_manager.debug.d -c -o .register_manager.debug.o register_manager.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .remote.debug.d -c -o .remote.debug.o remote.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .selection.debug.d -c -o .selection.debug.o selection.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .selectors.debug.d -c -o .selectors.debug.o selectors.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .shared_string.debug.d -c -o .shared_string.debug.o shared_string.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .shell_manager.debug.d -c -o .shell_manager.debug.o shell_manager.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .string.debug.d -c -o .string.debug.o string.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .unit_tests.debug.d -c -o .unit_tests.debug.o unit_tests.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .window.debug.d -c -o .window.debug.o window.cc
clang++ -DKAK_DEBUG -I/usr/local/opt/ncurses/include -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .word_db.debug.d -c -o .word_db.debug.o word_db.cc
a2x --no-xmllint -f manpage ../doc/kak.1.txt
make: a2x: No such file or directory
make: *** [../doc/kak.1.gz] Error 1
make: *** Waiting for unfinished jobs....

Error: kakoune was moved to homebrew-boneyard because it has unfixable issues.
Please do not file any issues about this. Sorry!
~$ which a2x
/usr/local/bin/a2x
~$
```

**Comment by lenormf** [comment] 2016-12-14 08:49
Is it possible that you had `asciidoc` installed prior to building kakoune, and that the `a2x` script was installed in a directory that is not in the `PATH` used when `homebrew` builds recipes?

Can you try removing `asciidoc`, then installing `kakoune` and let `homebrew` install that dependency itself?

**Comment by cvlmtg** [comment] 2016-12-14 08:56
@supermarin you're using the wrong recipe. as written in kakoune's readme, use

```
brew tap homebrew/dupes
brew install homebrew/dupes/ncurses
brew install --HEAD https://raw.githubusercontent.com/mawww/kakoune/master/contrib/kakoune.rb
```

it works for me on sierra. I think the problem here is that there are 2 recipes, one of which is not working.

**Comment by lenormf** [comment] 2016-12-14 10:02
We'll have to make a PR to update that upstream recipe, thanks for bringing that up.
