### ISSUE TITLE
Cannot quote string ending in backslash

### ISSUE THREAD

**Issue by danr** [mawww/kakoune#1221] opened 2017-02-15 13:53 UTC
When using `'` `"` and `%~`-style quotes, a string ending with a backslash  cannot be quoted. For example, this fails:

    echo %~\\~
    
I know that `%{`-style qutoes can end with a backslash, like so:

    echo %{\}

But the drawback with these is that `}` cannot be escaped, and there are only four of them, so if you need all of `>})]` this is not an  alternative.

There should be a way to quote any string.

**Comment by lenormf** [comment] 2017-04-14 15:33
Dupe of #1049.

**Comment by mawww** [comment] 2018-05-12 22:48
Closing as a duplicate of #1049

**Closed by mawww** 2018-05-12 22:48 UTC
Labels: bug
